const languages = {
    en: {
        title: 'Form title',
        first_name: 'first name',
        last_name: 'last name',
        email: 'email',
        company: 'company',
        city: 'city',
        message: 'message',
        send: 'send',
    },
    ru: {
        title: 'Название формы',
        first_name: 'Имя',
        last_name: 'Фамилия',
        email: 'E-mail',
        company: 'Компания',
        city: 'Город',
        message: 'Текст сообщения',
        send: 'Отправить',
    },
    ar: {
        title: 'لقب شكل',
        first_name: 'اسم',
        last_name: 'لقب',
        email: 'البريد الإلكتروني',
        company: 'شركة',
        city: 'مدينة',
        message: 'رسالة',
        send: 'يرسل',
    },
}
